FROM node:22-alpine

WORKDIR /json-server

COPY src/app/data/package.prod.json /json-server/package.json
RUN npm install

COPY src/app/data/db.json /json-server/db.json
COPY src/app/data/server.js /json-server/server.js

EXPOSE 3000

CMD ["node", "server.js"]
