FROM node:22-alpine AS angular-build

WORKDIR /angular-app

RUN npm install -g @angular/cli

COPY package*.json ./

RUN npm ci

COPY . .

RUN ng build --configuration=production


FROM nginx:1.27-alpine

COPY --from=angular-build /angular-app/dist/built-app/browser /usr/share/nginx/html
COPY docker/default.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx.conf /etc/nginx/nginx.conf

WORKDIR /nginx-app

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
